# Generated by Django 2.2.9 on 2020-03-18 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0016_integralgoods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='shop_price',
        ),
    ]
