# Generated by Django 2.2.9 on 2020-03-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0017_remove_goods_shop_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_introduce',
            field=models.TextField(default='', max_length=500, verbose_name='商品介绍'),
            preserve_default=False,
        ),
    ]
