# Generated by Django 2.2.9 on 2020-04-22 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0022_auto_20200422_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='fav_num',
            field=models.IntegerField(default=100, help_text='收藏数', verbose_name='收藏数'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_brief',
            field=models.TextField(help_text='商品描述', max_length=500, verbose_name='商品描述'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_introduce',
            field=models.TextField(help_text='商品介绍', max_length=500, verbose_name='商品介绍'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_num',
            field=models.IntegerField(default=100, help_text='库存数', verbose_name='库存数'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='is_discount',
            field=models.BooleanField(default=True, help_text='是否可以用优惠券', verbose_name='是否可以用优惠券'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='is_hot',
            field=models.BooleanField(default=True, help_text='是否放上首页热销栏', verbose_name='是否放上首页热销栏'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='is_new',
            field=models.BooleanField(default=False, help_text='是否放上新品栏', verbose_name='是否放上新品栏'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='is_normal',
            field=models.BooleanField(default=True, help_text='是否为上架商品', verbose_name='是否为上架商品'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='is_refund',
            field=models.BooleanField(default=False, help_text='是否支持退款', verbose_name='是否支持退款'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(help_text='商品名', max_length=100, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='sold_num',
            field=models.IntegerField(default=100, help_text='商品销售量', verbose_name='商品销售量'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='storage_type',
            field=models.CharField(default='常温', help_text='存储方式', max_length=30, verbose_name='存储方式'),
        ),
    ]
