# Generated by Django 2.2.9 on 2020-04-23 21:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0023_auto_20200422_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerindex',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='bannerindex',
            name='image',
            field=models.ImageField(help_text='轮播图片', upload_to='banner', verbose_name='轮播图片'),
        ),
        migrations.AlterField(
            model_name='bannerindex',
            name='name',
            field=models.CharField(default='', help_text='轮播图名字', max_length=30, verbose_name='轮播图名字'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commenttext',
            field=models.CharField(help_text='商品评论', max_length=200, verbose_name='商品评论'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='goods',
            field=models.ForeignKey(help_text='商品', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='goods.Goods', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.IntegerField(default=5, help_text='商品评分', verbose_name='商品评分'),
        ),
        migrations.AlterField(
            model_name='goodscategoryall',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='goodscategoryall',
            name='icon',
            field=models.ImageField(blank=True, help_text='图标', null=True, upload_to='icon/', verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='goodscategoryall',
            name='image',
            field=models.ImageField(blank=True, help_text='类别图片', null=True, upload_to='category/', verbose_name='类别图片'),
        ),
        migrations.AlterField(
            model_name='goodscategoryall',
            name='is_show',
            field=models.BooleanField(default=False, help_text='是否放在首页分类展示', verbose_name='是否放在首页分类展示'),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='goods',
            field=models.ForeignKey(help_text='商品', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.Goods', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='image',
            field=models.ImageField(blank=True, help_text='图片', null=True, upload_to='goods/banner/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='index',
            field=models.IntegerField(default=0, help_text='轮播顺序', verbose_name='轮播顺序'),
        ),
        migrations.AlterField(
            model_name='goodsspecification',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='goodsspecification',
            name='goods',
            field=models.ForeignKey(help_text='商品', on_delete=django.db.models.deletion.CASCADE, related_name='specification', to='goods.Goods', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='goodsspecification',
            name='promotion_price',
            field=models.FloatField(blank=True, help_text='促销价格', null=True, verbose_name='促销价格'),
        ),
        migrations.AlterField(
            model_name='goodsspecification',
            name='shop_price',
            field=models.FloatField(default=0, help_text='商品价格', verbose_name='商品价格'),
        ),
        migrations.AlterField(
            model_name='goodsspecification',
            name='specification_text',
            field=models.CharField(help_text='商品规格', max_length=100, verbose_name='商品规格'),
        ),
        migrations.AlterField(
            model_name='integralgoods',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='添加时间', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='integralgoods',
            name='goods_num',
            field=models.IntegerField(default=100, help_text='库存数', verbose_name='库存数'),
        ),
        migrations.AlterField(
            model_name='integralgoods',
            name='image',
            field=models.ImageField(blank=True, help_text='图片', null=True, upload_to='goods/integralgoods/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='integralgoods',
            name='integral',
            field=models.CharField(help_text='需要的积分', max_length=100, verbose_name='需要的积分'),
        ),
        migrations.AlterField(
            model_name='integralgoods',
            name='name',
            field=models.CharField(help_text='商品名', max_length=100, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='integralgoods',
            name='specification',
            field=models.CharField(help_text='商品的规格', max_length=100, verbose_name='商品的规格'),
        ),
    ]
